CREATE TABLE [dbo].[SR](
	[ID] [int] NOT NULL,
	[Unique] [varchar](50) NOT NULL,
	[PEOPLE_ID] [int] NOT NULL,
	[POSITION_ID] [int] NOT NULL,
 CONSTRAINT [PK_SR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
